---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - nifi.kubedoop.dev
  resources:
  - nificlusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nifi.kubedoop.dev
  resources:
  - nificlusters/finalizers
  verbs:
  - update
- apiGroups:
  - nifi.kubedoop.dev
  resources:
  - nificlusters/status
  verbs:
  - get
  - patch
  - update
