---
apiVersion: zookeeper.kubedoop.dev/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple-zk
spec:
  clusterConfig:
    listenerClass: cluster-internal
  servers:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: zookeeper.kubedoop.dev/v1alpha1
kind: ZookeeperZnode
metadata:
  name: simple-nifi-znode
spec:
  clusterRef:
    name: simple-zk
---
apiVersion: authentication.kubedoop.dev/v1alpha1
kind: AuthenticationClass
metadata:
  name: simple-nifi-admin-user
spec:
  provider:
    static:
      userCredentialsSecret:
        name: simple-nifi-admin-user-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: simple-nifi-admin-user-secret
stringData:
  # The admin user is required for a working single user NiFi deployment. The password can be changed as desired.
  admin: admin
  # Will not be read and used by NiFi (e.g. in case of reusing a Secret)
  bob: bob
---
apiVersion: nifi.kubedoop.dev/v1alpha1
kind: NifiCluster
metadata:
  labels:
    app.kubernetes.io/name: nifi-operator
    app.kubernetes.io/managed-by: kustomize
  name: nificluster-sample
spec:
  clusterConfig:
    authentication:
      - authenticationClass: simple-nifi-admin-user
    listenerClass: external-unstable
    sensitiveProperties:
      keySecret: nifi-sensitive-property-key
      autoGenerate: true
    zookeeperConfigMapName: simple-nifi-znode
  nodes:
    config:
    roleGroups:
      default:
        replicas: 1
